server:
  port: 8072
  
logstash.host: 3.136.161.26:5000

logging:
  level:
    io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor: ERROR
  
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
        - RemoveRequestHeader= Cookie,Set-Cookie
      - id: course-service
        uri: lb://course-service
        predicates:
        - Path=/course/**
        filters:
        - RewritePath=/course/(?<path>.*), /$\{path}
        - RemoveRequestHeader= Cookie,Set-Cookie
      - id: enrollment-service
        uri: lb://enrollment-service
        predicates:
        - Path=/enrollment/**
        filters:
        - RewritePath=/enrollment/(?<path>.*), /$\{path}
        - RemoveRequestHeader= Cookie,Set-Cookie
   
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    propagation:
      type: w3c
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
